services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8889:8080"
    volumes:
      - ./docker/searxng/settings.yml:/etc/searxng/settings.yml:ro
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
